---
lowercaseOutputName: true
rules:
   - pattern: metrics<name=(.*?)\.(.*?)\.(.*?)\.(.*?)\.(.*?)\.(.*?)\.*>
     name: $1
     labels:
       direction: $4
       fpsType: $3
       messageType: $2
       txSts: $5
       stsRsn: $6
     type: COUNTER
   - pattern: metrics<name=(.*?)\.(.*?)\.(.*?)\.(.*?)\.(.*?)\.*>
     name: $1
     labels:
       direction: $4
       fpsType: $3
       messageType: $2
       txSts: $5
     type: COUNTER
   - pattern: metrics<name=(.*?)\.(.*?)\.(.*?)\.(.*?)\.*>
     name: $1
     labels:
       direction: $4
       fpsType: $3
       messageType: $2
     type: COUNTER